version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"  # Порт FastAPI
    depends_on:
      - frontend
    environment:
      - ENV_VARIABLE=example
    volumes:
      - .:/backend

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"  # Порт React
    environment:
      - REACT_APP_API_URL=http://backend:8000  # URL для обращения к бэкенду