version: "3"
services:
  fastapi:
    build:
      context: ../fastapi-react/backend/app
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"

  react:
    build:
      context: ./my-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - fastapi